# Generated by Django 4.2.5 on 2024-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_remove_computerhistory_operating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operating_system',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
